"""Trusted execution surface for TacoRank experiments."""

from tacorank.execution.commands import (
    REQUIRED_COMMAND_IDS,
    CommandContext,
    CommandPolicyError,
    CommandProfile,
    CommandRegistry,
    ExpectedArtifact,
    PipelineCommandInputs,
    ResolvedCommand,
    default_command_registry,
)
from tacorank.execution.artifacts import (
    EXECUTION_SEAL_FILENAME,
    EXECUTION_SEAL_SCHEMA,
    ExecutionSealVerificationError,
    verify_execution_seal,
)
from tacorank.execution.interfaces import (
    CanonicalArtifactStoreAdapter,
    ExecutionArtifactStore,
    SharedSchemaUnavailable,
)
from tacorank.execution.runner import (
    DenyUnverifiedExecution,
    ExecutionAuthorizationError,
    ExecutionRunner,
    FakeExecutionRunner,
    InvalidRunRequest,
    RunnerPolicy,
    SubmissionArtifactResolver,
)
from tacorank.execution.seals import (
    ReceiptArtifactBinding,
    ReceiptArtifactResolver,
    SealedExecutionVerifier,
    VerifiedExecutionSeal,
)
from tacorank.execution.sandbox import (
    ContainerMountPolicy,
    ContainerReadOnlyMount,
    DedicatedFilesystemQuotaVerifier,
    DockerSandbox,
    ExecutionSandbox,
    IsolationGuarantees,
    ImageEnvironmentProof,
    LaunchSpec,
    OutputQuotaProof,
    OutputQuotaVerifier,
    ResourceLimits,
    RuntimeCleanupSpec,
    RuntimeMetricsSpec,
    SandboxConfig,
    SandboxPolicy,
    SandboxPolicyError,
    TrustedLocalProcessSandbox,
    validate_launch_spec,
)

__all__ = [
    "REQUIRED_COMMAND_IDS",
    "CommandContext",
    "CommandPolicyError",
    "CommandProfile",
    "CommandRegistry",
    "CanonicalArtifactStoreAdapter",
    "ContainerMountPolicy",
    "ContainerReadOnlyMount",
    "DenyUnverifiedExecution",
    "DedicatedFilesystemQuotaVerifier",
    "DockerSandbox",
    "EXECUTION_SEAL_FILENAME",
    "EXECUTION_SEAL_SCHEMA",
    "ExecutionAuthorizationError",
    "ExecutionArtifactStore",
    "ExecutionRunner",
    "ExecutionSandbox",
    "ExecutionSealVerificationError",
    "FakeExecutionRunner",
    "ExpectedArtifact",
    "InvalidRunRequest",
    "IsolationGuarantees",
    "ImageEnvironmentProof",
    "LaunchSpec",
    "OutputQuotaProof",
    "OutputQuotaVerifier",
    "PipelineCommandInputs",
    "ReceiptArtifactBinding",
    "ReceiptArtifactResolver",
    "ResolvedCommand",
    "ResourceLimits",
    "RuntimeCleanupSpec",
    "RuntimeMetricsSpec",
    "RunnerPolicy",
    "SandboxConfig",
    "SandboxPolicy",
    "SandboxPolicyError",
    "SealedExecutionVerifier",
    "SharedSchemaUnavailable",
    "SubmissionArtifactResolver",
    "TrustedLocalProcessSandbox",
    "VerifiedExecutionSeal",
    "default_command_registry",
    "validate_launch_spec",
    "verify_execution_seal",
]
